In [1]:
import pandas as pd


df = pd.read_parquet(rf"C:\Users\sus14836\Downloads\WHU-RS19.parquet")

In [2]:
df

                                                  image  label
0     {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...      0
1     {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...      0
2     {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...      0
3     {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...      0
4     {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...      0
...                                                 ...    ...
1000  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...     18
1001  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...     18
1002  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...     18
1003  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...     18
1004  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...     18

[1005 rows x 2 columns]

In [4]:
df['image'].iloc[562]

{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x01\x00H\x00H\x00\x00\xff\xe17\x90Exif\x00\x00MM\x00*\x00\x00\x00\x08\x00\x07\x01\x12\x00\x03\x00\x00\x00\x01\x00\x01\x00\x00\x01\x1a\x00\x05\x00\x00\x00\x01\x00\x00\x00b\x01\x1b\x00\x05\x00\x00\x00\x01\x00\x00\x00j\x01(\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\x011\x00\x02\x00\x00\x00\x1c\x00\x00\x00r\x012\x00\x02\x00\x00\x00\x14\x00\x00\x00\x8e\x87i\x00\x04\x00\x00\x00\x01\x00\x00\x00\xa4\x00\x00\x00\xd0\x00\n\xfc\x80\x00\x00\'\x10\x00\n\xfc\x80\x00\x00\'\x10Adobe Photoshop CS3 Windows\x002010:01:10 16:12:55\x00\x00\x00\x00\x03\xa0\x01\x00\x03\x00\x00\x00\x01\xff\xff\x00\x00\xa0\x02\x00\x04\x00\x00\x00\x01\x00\x00\x02X\xa0\x03\x00\x04\x00\x00\x00\x01\x00\x00\x02X\x00\x00\x00\x00\x00\x00\x00\x06\x01\x03\x00\x03\x00\x00\x00\x01\x00\x06\x00\x00\x01\x1a\x00\x05\x00\x00\x00\x01\x00\x00\x01\x1e\x01\x1b\x00\x05\x00\x00\x00\x01\x00\x00\x01&\x01(\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\x02\x01\x00\x04\x00\x00\x00\x01\x00\x00\x01.\x02\x02\x00\x04\x00\x00\x00\x01\x00\x006Z\x00\x00\x00\x00\x00\x00\x00H\x00\x00\x00\x01\x00\x00\x00H\x00\x00\x00\x01\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00H\x00H\x00\x00\xff\xed\x00\x0cAdobe_CM\x00\x02\xff\xee\x00\x0eAdobe\x00d\x80\x00\x00\x00\x01\xff\xdb\x00\x84\x00\x0c\x08\x08\x08\t\x08\x0c\t\t\x0c\x11\x0b\n\x0b\x11\x15\x0f\x0c\x0c\x0f\x15\x18\x13\x13\x15\x13\x13\x18\x11\x0c\x0c\x0c\x0c\x0c\x0c\x11\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x01\r\x0b\x0b\r\x0e\r\x10\x0e\x0e\x10\x14\x0e\x0e\x0e\x14\x14\x0e\x0e\x0e\x0e\x14\x11\x0c\x0c\x0c\x0c\x0c\x11\x11\x0c\x0c\x0c\x0c\x0c\x0c\x11\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\xff\xc0\x00\x11\x08\x00\xa0\x00\xa0\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xdd\x00\x04\x00\n\xff\xc4\x01?\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x01\x02\x04\x05\x06\x07\x08\t\n\x0b\x01\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x10\x00\x01\x04\x01\x03\x02\x04\x02\x05\x07\x06\x08\x05\x03\x0c3\x01\x00\x02\x11\x03\x04!\x121\x05AQa\x13"q\x812\x06\x14\x91\xa1\xb1B#$\x15R\xc1b34r\x82\xd1C\x07%\x92S\xf0\xe1\xf1cs5\x16\xa2\xb2\x83&D\x93TdE\xc2\xa3t6\x17\xd2U\xe2e\xf2\xb3\x84\xc3\xd3u\xe3\xf3F\'\x94\xa4\x85\xb4\x95\xc4\xd4\xe4\xf4\xa5\xb5\xc5\xd5\xe5\xf5Vfv\x86\x96\xa6\xb6\xc6\xd6\xe6\xf67GWgw\x87\x97\xa7\xb7\xc7\xd7\xe7\xf7\x11\x00\x02\x02\x01\x02\x04\x04\x03\x04\x05\x06\x07\x07\x06\x055\x01\x00\x02\x11\x03!1\x12\x04AQaq"\x13\x052\x81\x91\x14\xa1\xb1B#\xc1R\xd1\xf03$b\xe1r\x82\x92CS\x15cs4\xf1%\x06\x16\xa2\xb2\x83\x07&5\xc2\xd2D\x93T\xa3\x17dEU6te\xe2\xf2\xb3\x84\xc3\xd3u\xe3\xf3F\x94\xa4\x85\xb4\x95\xc4\xd4\xe4\xf4\xa5\xb5\xc5\xd5\xe5\xf5Vfv\x86\x96\xa6\xb6\xc6\xd6\xe6\xf6\'7GWgw\x87\x97\xa7\xb7\xc7\xff\xda\x00\x0c\x03\x01\x00\x02\x11\x03\x11\x00?\x00\xc3\xbb\x19\xb7>\xbcv\xd7\xb2\xdfM\xe4R\x18\xd7zfK\xa9\xc4\xc7\xa9\xce\xad\xdb\xabkv^\xda\xdf\xfd#\xf9\xff\x00\xa0\xact\xff\x00\xaf]m\x82\xecLL6u7d\xdf\xbf\x1e\xbb\xbdK^\xc7\xb5\xbbY\xe9\xee\xb2\xea\xdd]mk,\xaf\x19\xaf\xf4\xf1\xec\xfee\x0b\xf6}x\xf8\xfe\xafR\xba\xcck]Iw\xa6\xc6\x8d\xefk\xff\x00\x9efN\x9b\xeb\xb7*\xc7}\x9e\xc6\xd1\xea~\x89\x9e\x9eJ\xa8\xfe\xafuY\x15^\xda\xcf\xa7S\x08f9>\x93\x01-\xdb\xfa\xc6\xcf\xdd\xdd\xb3\xd2\xa7\xf9\xdf\xf8\xaf\xa7\x14Mm\xaa\x8a[\xfag]f)\xb3\xa8\xe4\xd5vC\xc1~CA6\xdf\x00\x86\xfa\xb6\xdc\xd1\xe9\xbf)\x9f\xc8\xcb\xf5l\xaf\xfd2\xd5\xe8\xdd|\xf4z\x1b\x8f\x0c\xea\x9d1\x8e\xdd\x97\x95V\xe3\x90\x1a\xd2\xdbk\xb7m\x8e\xad\x8d\xb5\xaf\xdb\xfa/\xe7\xd9O\xe7\xfa\x9e\x9d\xd6ec\xd3u\x8f~3\xa8{r\xb2\x0bE\x95[\xe95\xb56\xb0K^jy\xa9\xec\xaa\x86\xff\x007\x99S\xee\xafg\xf8?\xb4\x7f;\x0c\x9c\xec\xdc\\\x8f\xb3\xf5\n\xab\xb5\xf8\xda\x0f]\xa1\xc4\xb5\xe7\xf4o\xf5\x9d\xb7&\xcd\xde\xcd\xbf\xe8=\xff\x00B\xd4o^\x9d\xd4d\xd8\xea\x1dS\x1a\x9d\xbf\xb2s>\xd7eM\x9c\xa7\xdb[X\xd7\xfa\xbb\xa1\xa3\x17m~\x9d\xf4\xdd\xed\xb2\x9f\xf4\x9e\x9f\xa7w\xf3\x88\x15e\xfa\xf6\xd7u\xe2\xd6\xd9t>\xb7\xb6\xb6\x89\x02}K[\x8fG\xb6\xdal\xb7\xfc?\xf3\xaf\xf4\x93a\xe1\xd9\xd5\xace\xb8\xc5\xdble\x87&\xb7\x1d\xceq\xfee\xd5\xe3\xdfc\x9bN\xeb\xac\x1f\xa9\xe3\xdf\xfaO\xd1\xff\x00\xd6\xd6m\x97U^@n=n\xb2\xd6\xbflXKK\x8b=\xbb\xfd\x85\x97\xb3\xfbU\xd7\xe9\xb3}HP\xd9\x12\xb7N\xccj3_u\xbdC/\xec\xad\x0e\xfd5\xdb\x9b\xe8\x11\r\xb2\xba\xb1\xbfG\xbf\xdbA\xaf\xec\xf5\xff\x00;\xfe\x17\xf4^\xfbn\x1e\x0b\r.\xd9\x87\x8fQd\xb6\xeb\xb33X\xe6\xcb6\xedk)\xbb 6\xdf\xd2Z\xff\x00\xfbM\xe8o\xb3\xfe\t\x13\xa4}\xb7#=\xf6\xb1\x95\xd9eB\xba>\xd2\xe0\xd7lp\xf6\xb6\xb1VC\xf1\xf1\xfe\x83\x7f\xc2\xbe\xbb\xac\xd9\xfe\x91,\xe6f_\xd4\'\xaa_[\xc3A\xbe\xd6U\r\xdf\x1b\xed\x1b\xedpo\xa1\xea\xb9\xd6{>\x9f\xe8\xbe\x9f\xab\xe9\xa5~*\xbd\x01Es0\x0f\xafnN=\xf8\xe5\xe4\xda\xdc\xc7;k\xdcF\xe3\x1e\xad\xad\xb2\xa6z\x8c\xfeb\xb6T\xcf\xd2~\x8f\xd5C\x17\xb0c>\xf6_\xeb\xd7L\x80\xf3d[Y$WA\xf4\x9b\xb7\xd6c\xbdO\xf4{?\x9c\xff\x00F\xaff\xfd\x8bp\xc9\xc9\xc7\xc8\xcb\r\x15\xb9\x966\xca\xc6+X\xd1-\xf5q}:\x9f]\x94V\xf7}\x9e\xac\xafZ\xcb\xff\x00\xe1*\xb1ed\\\xec\xcb\xfe\xcf\x85H\x0ck\x8b\xeb\xda\xd6Wf\xe8\xd9]\x96\x8c\x7fN\x9a+\xfd\'\xbf\xf9\xba\xe9\xb3\xfd\x12@YA\t\x1e\xc2)e\xb98\xd5ec\xd9-\xab\xa8b\xeeii?F\xb7z{\x9b\xeaW\xfe\x86\xfa\x9f\xff\x00\x03\xbdj\xe1\xe1\xdd\x8d\x8c\xdc\xdc\xb0*\xa1\xad.\xa9\xce\xa8\xbf!\xb0=6;{=[q\xab\xd5\xbe\xff\x00\xd2Y\xfe\x16\xbfC\xfc\x1bcR\xdc+}l\xb3[\xf3\xb6{\x9fMa\xc1\x82[\xef\xc8\xd8\xdfS#\xd5\xf7\xfa\xd9\xbf\xf5\xcc\x1f\xf0\xb6\xa7\xbb<\x8c\xc7\xdaK-\xb5\xe4\xfa8\xf2\xe7W#\xf9\xcb/\xf4v[s]\xfe\x8d\xdfg\xc6\xf5?Kw\xafeh\xd8\xd9W\xd9\x05\xb94T\xef\xd4\x89\xc8\xc9\x03sh\xaf\xd4uU\x87\x1f\xa6\xfb\xac\xf4sls\x7fu\xcc\xdfg\xf3\x9e\xb5J\x96I"\xd2\xfb\xed\xb6\xc7\xb5\xa4\x01[\xb6\xc0:CZ\xd0\xd6\xfb\x9c\xff\x00\xf8\xbf\xfd\x18{\xeb\xb4\xd9\xfa\x8d\xdb1\xde\xf2^\xc1X\xabq\x1e\xdfk\xe8w\xac\xf6\xfem^\xb7\xa6\xa0\xfa\xee\x0e\x1e\xb63X\xf7\x9f\xa6\xd7\x1d\x85\xe0\xea,\xaf}\xb59\xfb\xbf\xc0\xb1\xdf\xf5\xbfJ\xbfI*\xb5\x05\x87W\xc9\xa6\xb0\xd1k\xeft};a\xedk\x00\xfd\x1e\xcd\xe1\xdf\xcd\xc7\xef\xfe\x8dG\x1e\xaf\xb5X=J\xea\xae\x90\tkX6\x98h.w\xa8\xe7\xee\xb2\xb7\xd8\xef\xdfw\xe8\xff\x00\xd1(\x9c|\x86\xd4n}\x87u\x8ec\xab\rq\xdc_%\xadkg\xdf\xec\xff\x00\x83g\xb1^\xc6f\xeb\xece\xa07\x18\x17;c\x1d\r\xdd_\xb5\xf6\x16\xb5\x8d\xde\xff\x00\xea\xff\x00\xdb\xbb\x12\xd9%\xbf\x91\x91\x86E\x15\xe5\xda\xce\x9fO\xb6\xd3C\x88-\xf4\x80\xf6V\xc6\x7f;\xef\xddg\xa7W\xf3_\xa5\xf5k\xf5U\x0b\xba\xbe%\xac5\xd1fE\x99\xaek1\xab\xb7\xd1\xda+\x0f3c\xf4\xfd#\xb2\x1a\xd7\xfaT\xfe\xaf\xea\xff\x00\x85\xaf\xfd*\xadu\x98\x96^\xe6c\xb1\x97\xfb\x89\xbf-\xec\x16X\xe7\x926\xd1_\xad\xbb\xfa3\x7fE\xee\xfe~\xdf\xf85\xbbMU\xf4\xd6\x07\x1cm\xf6\x80\xc2\xebY\x00\x02\xe75\xde\x95{\xf6\xba\xad\xacs\xfdm\xbf\xe7\xfait\xb3jr\xb3\xba\xa6%6\x1cm\x8d\xad\xf5V\xca@mD\x92[\x0c\xdc\\?\xab\xb7\xe9\xfe\xff\x00\xf3\xa8\x95X\xc7gS]M\x00\x1a\x9bp\xdd\x1b\xcc\x97\xd8,\xb8\xeb\xfaK\x1a\xef\xdf\xfek\xd3\xf5=Ek\x0f6\xeb3YqsK-u\x85\x8e\x1a\x86\x17\xba\xc7SC\x9e}\xde\xf63m\x7f\xcd\xd4\xab\x8b\x19\x95\xd5^Z\x1c\x0b\xda\xefq\x81\xbbR6\xb7v\xef\xd3W\xff\x00\x9e\xbf\x9dKDS\xff\xd0\xe5le\x9bF;\xed\x16\xe3\x98\xb1\xd7\xce\xe7V\x1d\x0e\xba\xc6\xd7\xab\xdd\xeco\xa4\xcfo\xa1k\xde\x9b&\xf6\nZ\xf84\xd4w\x9cw\x90-\xb5\xe3\xbd\x97\xbc\xcdU~\x93\xd8\xcfO\xf4\xbf\xce [\x86\xc7\\[\xeek\xdb\xa3\xdaIs\xc3\xb7m~\xd77s\x9d\xb1\x8dw\xef\xab\x98X\xf5\x9b\xbdK\xab\x0f"\x05u\x97\x179\xdf\xd9\xfa\x16\xfa\x7f\x9b\xfb\xf6\xff\x00\x84L#\xc1m\xdbo\x17(`\xe03%\xd4>\x87\x8a\xcbje\x81\xcf\xa9\xc7\xfc\x1f?\xa2f\xfb\xbf5\xf5\xe3\xd7W\xe8\x95oS\x1e\xd6\xe1\xe1:\x9a\xc5m>\xa3\x8d\xcd\x97:\xcb?\xa5\xe4]u\xa6\xef\xd17\xf9\xba\xb7\x7f\xd7?\xc1\xab\x19\xf5Y[]S.\x87?\xe9T\xe2\x00\x91\xfb\x8d\xdc\x1a\xc7\x7f\x83z\xcee\xf7\xd5C\x9b\x95P4\xd0\xefq\xb2\x1aD\xee\xf4\xe9\x0c?\xa5\xddo\xbbg\xa9\xfaOM6\x8e\xa52\x05Y>\x8e]M\xae\x9b\x06=\xd6\xdb\xe9\xd3\x88\xc6\x82\xcb\x00n\xd6\xe4Y\x8f\xfd\x1e\xaf\xdc\xdf\xfc\xe6\xcf\xdfMg\xa6\xe0(\xc1\xc4\xb6\xf3K\x1a\xdc\xdb\x08\x16K\xd93\xea[\x0f\xdc\xdb6\xbf\xd3\xaf\xf3*g\xe8w\xff\x00\x85\x87M\xcf\xc4\xc4\xcce\xafe\xac\xc7:\xde\xfa\x8b}g\xee>\xda]s\x87\xb5\xafp\xf7\xecs?\xebJ\xc6\x1eVE]8\xd1]5\xbb\x16\xc7\xba\xe6\xd4\xfb]Ec\xdd-\xb2\xc7\xb3\xd1\xb2\xdf\xdc\xc7g\xda\x7fH\xff\x00\xf0VW\xe8"\x81\xb6\xac\x9b\x93e\x15\xbb5\xd47\x12\xb8\x0c\xa6\xa0\xe6T\xdd\xa0m\xd9e\x7fN\xed\xcf\xdds\xf6\xe2]g\xfc-vW\xea\xaa.\xcd\xcd\xb5\xce\xf4Ci\xa9\xce\xf5\x00~\xdbd\x82\xed\x9e\xbd\xd75\x8c\x7f\xb3\xd9\xbbf\xcf\xf0_\xcd-\x07\xf4~\x9dN\x19\xea\x17e\x8c\xbb\x1a\xe6\xefu:P\xd2\xf1\xf6\x86\xd2\xcb\x1c}z\xdd\xb7si\xfdS\xf9\xef\xd1\xff\x00-\x06\xbbC\x99\xbd\xc2\xaa[l\x16\x17\xfb\xcd\x8dh/\x8c\x8b\x06\xd7;\xdc\xd6\xfb\xf6\xfa>\xa5\x7f\xcd +}\xd4Eo\xab6:\xb7c\xfa}Js\xb7\xbb\xd4\xbe\xc2\xd79\x95\xba\xc0\x0b6\\\xc3]\xbfhtW\xebW\xfa\x1a\xecg\xe8?\xc1!\x16\x96\\\\hc\x01p\x0ce\x0e\x1e\x96\xf1\x02\xb3\xb0\xb5\xafv\xdf\xf4j\r\xb5\xce\xb1\xcc\xbd\xa5\xa0\x02\xd70\xc3\x9aI\x1f\x9d\xbf\xf3}\xbe\xcd\xe8\xb5Y_\xae\xcc\x8a\xc45\x8d\x92X[\xab\x9a\'g\xb8\xfa{}O\xa1\xbf\xd6H\x95\x84\x93\xa1^\xcc\xdc\x9cw\x9c:6\xefk\xbfL\xed\xa1\xed.\x0f\xf73|[]\xb5\xee\xd9\xfc\xed_\xce\xad\x0c^\x95mUz\xb9\x16WX\x06,s\xc8u\x8e\xb4\x89\xfda\xda\xfa-f\xdf\xd23o\xd0Tzc\x1b\x8f}\x99\x966\x0e3v\xd6\xc7n\x97\xdc\xfd\xc5\xaf\xb4z\x97{\xdb\xb3\xf9\xba\xdf\xff\x00[\xde\xb4\xb2\xb3\x1bv#r3\x1d\xe9\xe3\xbd\xb1UUm6\xbe\xeb\x0f\xe9\x1f\xe96\xcd\xf65\x9f\xa7e?\xe8l\xfew\xd4\x7f\xe8\xd0\x91\xad\x07\xda\xc9\x1a\x00\xf94MO\xd2\x9c\x87\xfd\x9d\x85\xdb\xde\xd0\\I`\x0ef\xe7o\xfd=\xbe\xa3\x9b\xb3c\x1b\xfe\x97b\xb6X\xf6\xd1\x8e\xed\xa4\xba\xcd\xf67M\xb0\x0e\xdfN\x18\xe7\xbf\xdf\xe8\xfa~\xa5~\xa7\xaa\xca\xbfs\xfc\x16n5v\xf5\x07\xba\xdf\xb3\xb5\xde\xb6\xf8\xc8\xb5\xefp\x01\x8d\x9b\x0f\xa6\x7fM\x93mm\xf4\xdbS?\x99\xff\x00\x06\xb4m\xb3-\xa0\xe5c\xb6\xbc\\r\x00c\xec\x0c\xbe\xc7\xbd\x83\xdd[\x19Y\xf4\xa8\xa1\x9b\xbf\xedG\xe9?\xd1#kPzL\xae\xf6\xdb\xeaV\xeb\xe4\xfa\x0e\x15\xbfi#\xfe\xd4z\xae{\xfdoI\xbb\xec\xaf\x13\xf4[?\x9d\xff\x00\x06\xa3\x92\x0e\x0b\x9d\xb0\xbfuc\xde\xe3\x04\x12>\x8c:??\x7f\xee~\x7f\xa7B3z\x86\xd6]fO\xe9\x1e\xe6\x8a\xe8\xaa\xa6\xd2kc\x1aw\xec\xb6\xe6\x9ak\xaa\xdf\xd2{\xbf\xe3+\xaa\xbfW\xfc\x1dL\xdb_\x90\xc6U\xb1\xd5\xba\xe36\x02&=\xc7kk{\xfd\xceg\xb9\x9f\x9b\xe9\xfb\x12\xb2\xa2i\xd0\xfa\xbc\xcc<fW\x97\x9e\xff\x00S%\xec-\xc4/\x04\x8a\x8b}\xd5\xbe\xdd\xc1\xcde\xb6\xef\xfdU\x8f\xf6W\xff\x00]\xf4\xd9\x1fS%\xb8\xf5\xfb}!\x91I\x93\xbd\xd4\x91\xbd\xa5\xdf\xa4\x9d\xd4\xd8\xd7\xd2\xed\xee\xf5=7\xff\x007\xfe\x15\x07)\xae\xae\xab\x1e\x1c\xd7\n\x89\xf4\xf6K\x9e\xd2\xed\x95Q\x8f\xeen\xcb=\x7f\xf8\xbf\xf0~\xff\x00\xdf@\xbf>\xdb7Ue\x03pk\x0b\x1a\xe7\x91f\xd6\x8d\x8d\x0f\x86\x067un\xdb\xff\x00\xa5R\xd4\xa6\xcf\x9539\xf8\xf4\xe1=\x98U\xbd\xefh\x97\xd8\xe1\xed\xa5\x86\x18\xd7\xbf\xd2#\xd3\xb2\xcf\xcd\xf7\xff\x00\xc6*\xf8ym\xc7\xbcZ\x1a^\xeak53\xd32\xddF\xcd\xbe\xff\x00\x7f\xa9m\xaes6\xd6\xcf\xd2Y\xfe\x11h\xe4}`\xc7kqF\x1be\x8c\xa9\xcd\xaf\xd5s\x03\x83\x9f\xb5\x8fg\xa3\xbb\xd3\x7f\xa7\xb7\xd9m\xdf\xce\xff\x00\xa2\xfew\xd4\xaa\xdf\xb0\xb8\x0c\x81\x92[\x91M\xc0U\x8f-{\xdf3\xe9ddYCYM/\xa7\xf7\xdb\xeb\xbe\xc4F\xa3QI!\xff\xd1\xcf\xaf\x17&\xba\x9c\xfa\xe8kZ\xc2\xdd\x804\x1d\xc4k\xfa\xc5\x9fO\xfa\xfb\x7fL\x91\xc3\x0c\xad\xcexs[!\xe1\xf1\xb2\xbd\xa0\xfa\x96ms\xdf\xea\xeck\xbf3\xfe\xb9\xfc\xb4\xf6S\xd4@\x1e\x9dUS.\x81k\xec%\x9b\xbcw\xb1\xbb\xff\x00\xe2\xf7\xfa\x1e\xaf\xfao\xf0*\xbb:E\xfe\xa8\xbb.\xcar/\x049\xa2\xd3\xea0\xba`9\xfe\xa6\xdfU\xdf\xc9\xaf\xd2\xab\xfe5\x03/\x10\xc45\xea\x86\xcc\x97E\x8e\xe9\xd68cU\xedvIn\xb68\xff\x00\x83\xa1\xad\xdc\xfbk\xf7n\xb2\xdf\xfa\xde>\xc5\x9ck\x19[(\xba\xd7\x97\x19{\xa9\x0c{\xac\x07\xdc\xcf_\xd1c\x9d\xea?\xdd\xb2\xbf\xb4[\xf9\xff\x00\xf1\xabO\xac\xda\xeav\x8b\xb75\xef\xfa!\xaei\x80d\x9fOk\xbdM\x9f\xf1\xcd\xb2\xbf\xed\xac\xcal#\n\xe3C\xd8\xc7\x13\xba\xc3\x01\x85\xcc\xe1\xbe\x8b\x9c\xc7;u.\xdf\xeeQ\x8f\xe4Wiz\x05g\n0\xf2\xec/\xa1\xaev\x9b\xedp\x16\xb9\xaepf\x8e\xa1\xa1\x95c:\xaf\xe6\x9f\xfa\x1fW\xd6\xff\x00\x08\xac\xd5n\x16M\xacc\xf2n\xbe\xd7\x02Y[j{\xc81\xfc\xcbZ\xd1\xea2\xebZ\xd6\xb2\xbf\xb2\xfa\xac\xff\x00\tj\xa7s\xad\xb0\x1b\x9c\xe7:\xcb\x0f\xbd\xce\xdb.q\xf6\xefs\x9c?6\xaf\xeb\xbd\xff\x00\xf8\x1a\r\xb5\xb2\x8b\x8dU\x97R\xe8%\xe6\xb2\xe0`\x8d\xce\xf78X\xd77k\xfd\xe9U\xaa\xc5\xde\xee\x9d\xf8\xfd:\xa1o\xec\xeb\xdd\x93pk\x85\xcd\xf6\x00\x1a}\xde\x97\xd9\xf79\xbb\x9a\xff\x00\xd2\xdb\x7f\xfc\n\xafX\x0c\xc8g\xda\x9c\x1d\x8a\xe2\x01\x06\x19\xb9\xad\x1b\xb6n\xb3v\xcd\xfb\x9b\xb2\xef\xf0_\xa3\xfei\x0f\x1f\x0b\x15\xeemu\xba\xc3X\xfei\xb2\x06\xf7\x91\xef\x1b\xadg\xb2\xcd\x9e\xdf\xcc\xd9\xbf\xf4^\xf5}\xce\xc3\xa0\xdb\x92\xdb\x1c\xff\x00L\x8a\xad\xc2\xba\xb9\xb4\x10!\x94\xdb\xea;\x12\x8c|m\xfe\xa5\x9b\xe9\xc6\xfd]\x9f\xcez\xa8\x15\xdc<Z\xec\x84cd\xdd\x961\xb6\x97l;\xb1\xeb\xb9\xdc}\'}?f\xeb\x1f\xb3\xd3\xf5\x14\x9fex9\x17c\xd3w\xac\x0b\x85m{\x9d6\x074\xfbv1\xae\xf4{n\xf75\x9f\xa3\xff\x00G\xf4\xd0s:\x86;\xe8\xae\x8cg\x8a\xa8ea\xb6{I}\x9aC\xa8\xf5t\xfd\x13\x1d\xf4[[Y\xbf\xfc*\xaf{\xa9iqhi\xf6\x98,\xdc\xe6\x8da\xbe\x98xk\x7fKg\xa5\xec\xd8\x88\x1d\xd1\xc2\x06\xdd\xdbN}\x94`Z\xf6\xd4\xcb+7\xb2M\x9e\x9b@\xda\x0b\x19\x8e\xc6V\xf7\xedv\xcd\xfb\xea\xa7\xd5\xf4q\xff\x00\xe1\x14M\x94\xf5)\xc9v=5:\xad\xef\xb9\xf5\x07\xed\xb6\xbd\xc2\xb9\xdd\xb9\xd7\xfa\x8cg\xb7\xd0\xf5k\xdfG\xe9k\xab\xd4Y\xb5\xdbw\xa7\xb0d>\xb0\x08;F\xf7\x87\x10?\xd1K\xbe\x8c\xfd5\xa7\x93KG\xd9\xcbhnA\xae\xb6\x17\x12\x1d\xbe\xe1\x13\xed\x0c\x7f\xe8\x9f\xfe\x8d\x8c\xc6\xff\x00\x8d\xb1\xe8\xf0\xfd\xaaa^U\xee\xc7\xb0n\x8b,\x04\x13\xb4:\x1b;\xb6~s\x9b\xb2\xcd\x9f\xcd\xab\xe1\xde\xb5\x16ec\xd6Z\xcaX\xdcJ\xebk\xbd\xbe\x9b\x86\xcf\xb3\xdb\xa6\xfbY\xb9\xdb7\x7f;\xfaeC*\xfe\x9e\xc6\xb2\x9cH\xccw\xa6\t\xb0nf\xc7\xb8\x96z>\x9d\x8c\xfd-\xff\x00\xbc\xfa\xab\xfd\x0f\xe6)U\xd4i\x04\xb1\xd5\x83[\xdd\x17zv\x87\x1b\x1eN\xd6m\xa1\xe2\xb6:\xea\x7f\xc0\xda\xcfS\xd3\xfes\xfd\x12mu\xa4\x00F\x8d\xe6\xd2\xca\xec\x18{k\xdfA\xdc\r\x808\x12\xcft\xd9C\x8bZ\xfa\xac\xb6\xdfN\xda_\xfb\xf4\xfez\xa413*\xbe\x86\x06\xb7\xdcA\xac\xb4\x1a\xe7s\xb6\xbd\xcc7[\xe9\xff\x00#\xf4\x7f\xf5\x94G\xe6a\xd1\x82\xea\xf1q\xed\x19V\x87\xba\xf7\x86\xb5\x80\x12\xed\xedm\x8f~\xf7\xe42\xb6\x7f\x81\xf4\xff\x00\x9a\xff\x00=\r\xddG;7&\x9bl\xf4\xa9\x05\xadk\x03\x18\x1e\xc6\xb7\x8a\x9f\xfaW=\xac\x7f\xe8\xbf\xed\xcf\xf4\xa8\x8b\xff\x00}5\xe2\xde\xba\xa3\x7f\xa1\x85\x99s\xa8\xc3\xa8\xbb\'\xd3\xac\xba\xf79\xees\xe8k*\xaba\xfd3\xd9\xfc\xdf\xa5\xbf\xfc-\xdf\xe8\xd5\x0c\x8cz2\x1e\xf2\xe7\xe4\xe5S\xb8\xfa\x15\xd8\xe2\xe7\xb5\x8e?\xa0\x0e\xb6?\x9d\xb2\xb6n\xbf\xf9\xbf\xfc\t[u=J\xacv\xf5\xcc\xbc\x97}\xa9\xc4\xfd\x8e\xb65\x9b\xc6\xe0\xe3Y\r\xf5+u~\xd7o\xf4h\xa1\xf6X\xf7\xfe\x9a\xca}KV5\xac\xbe\xf7>\xf7\xdc\xfb\xc9\x1b\x9f\x04\xda\xe2\xc2G\xbd\xcdo\xf3{\xff\x00G\xfa\x17\xfe\x8f\xff\x00=\xa4\x01\xef\xf6&`\xe9F\x9b\xf4\xe1\xe3\x0c\x96^\xf1mt\x00\r\xd5T\xf2\xe0H>\x9f\xaam-\xfd&\xc6\xfen\xdf\xd2?\xe8+\xdd:\x9a\xa8\xa5\xec\xc4\xc5\xb2\xcc\xed\x84\xba\xc7m"\xa0\xe1\xfa[\xdfm\xacm8U\xd5\xb6\xc7\xfb\xbfKo\xfcZ\xc3\xc5\xc5}\xf7W\x8dF\xe7\xee\xf7\x16\xd6N\xb1\xf4\x18\xc6\xd4]\xef\xb1\xdf\xfa\xab\xd8\xaedd\xddS_C\xdc\xc1\x8a\xd7\x00hx\xf4\xfdG\xb7v\xe7\xfb\\\xed\xcde\x85\xde\xb6\xf7\xdd\xb3\xfc-H\xd1\xefh\x1a?\xff\xd2\xc4\xae\xdbCb\xec\x82\x19P\xf4\x99\xef\x8a\xc3f6R\xc0\xd3\xbb\xd8\xdd\x951\xacT\xf2\x8e00\xca\xdal\x8d\xa5\x81\xe4]\x07\xf3\xbdv7\xe8\x7f\xc0\xfd\x9b\xd3\xf4\x95\xfe\x8dV=\xd49\xf7\xd4,mO%\x85\xed\xe0{}1\xe9\x97zn\xdf\xfc\xe7\xe9+\xff\x00\xb6\xff\x00F\xafe\xdd\xd2\xeacq\xcd\xd8\xf42\xc3\x00l{co\xb9\xee\xbd\xacm6SW\xe6\xfd\xaf\x1f\xfd"\x8c\xc8m\xd5dA\xa2\xf2m\xc7m\xbe\xa9\xa3\x19\xc0\xf2\x01~\xe6\x86\x8f\xa5\xee"\x9fWkT\xab\x965\xcck\x1e\xe0\xf3\xa3\x83`=\x9e\r\xac\xee~\xefW\xf9_\x98\x8du\xd5\xe4?m^\xad\xb5\xb4\x08\x04m\x83\x1e\xef\xd1\r\xdb\xfe\x8e\xef[\xd9o\xfaUv\xe7? ;!\xad\xb3\'\x1e\xa6\x16\xe4d\x16\xb1\xb55\xee\x1b,\xa2\xcb\xdc[[\xf6o\xfev\xb7\xff\x00/\xf7\xd0\'\xc1CPt\xd9z0/\xa2[g\xe9L\x96X\x1a\xcb\x0c\x12[-w\xbf\xd7s\xfe\x86\xdd\x9f\xa0\xff\x00\x85U\xf2\xb0\xc7\xda\x9c\xca\x1b\x96\xcblt1\xcf\x0cyv\xe8\xfb=l\xbf\x18\xba\xbf\xcd~\xefS\xd3\xfd\x1a=\x17\x17:\xb1\x84\xf6\xc7\xb9\xdb\x9c\xc7\xc0pk\xbd-\x93\xe9\xb5\xfb\xb7\xff\x00=[\x9f\xec\xf5=%^\xdb\xb2\x9d\x93\xf6\x8b\xb6\x0fhw\xe8\x1df\xd0v\xfaTmfC\x9dO\xd1\xdf\xe9zI\xa2\xed:V\xa1\x19\xb0\x8b\x18\xdb\xc8\xa0\xb2k\xabs\x1c\xd6\x877w\xa8^^\xd65\xd9?\xe9v\x7f\xea\xcd{\xcfO~%n\xbc\xdb\xf6\x80\xc6\xba\xd3\x8e\xd0e\xa4\x9fN\xdb\xae\xddV;}\xad\xf6>\x87\xe3\xdbo\xe8\xff\x00\x9a\xfeiS\x16T\xd6\xd0E;\xe8\xb4\n\x98\x1b\xb4X\xe67\xf3\xff\x00M\xea\xd5\x97\xfao\xf0\x19\xad\xd8\xff\x00\xf06c\xd9\xe9\xe4&c\xf1*\xc8\xb4Y\x961\xf1\xe9\xd4T\xdd\xcd6\xbd\xdfK\xd3\xc7\xb1\xcf\xb3\xf4\xcdo\xa7u\x99l~=\x1f\xf7/\xfc";\x91]\x17G\x7f5\xd8\xfc\x11\x87\x93U\xf8\x8c\xae\xdd\xad\xc8k\xbd6\x02\xc6\xb4\x9d\xacx\xb0o}\xd94\xd9\xec\xfa\x1f\xa4\xb3\x1f\xfe\xb9E\xb5\xe2\r\xa2\xc6\xfaT\x92\xeb]X\xb0\x81X\xfa-c$5\xbb\xdf\xfe\x12\xcf\xfa\xdf\xf3u\xa5\x93\xd63\xae\xc9\x06\xa2\xd6\xb2\xbd\x18m\x0c\xb0\xfac\xe8\xb6\xe7Xne\xd8\xdf\x99[?\x9b\xa9,\xbb\xf1\\Y\x97\x91\x8e\xe8h\x0c\xf4\xaba\x14\x87\x10\xf3\xbfu\x8f\xb1\xed\xf5\xed\x1e\xb7\xa7\xea\xef}^\xcf\xe6Q\xd7\xed\xec\xb6^\x05/\xec\xd1\x91U\x99\x98u6\x8aY/\xa9\xb7>\x18\x1b\xbb\xd3\xa7k\xaak\x9c\xf7\xb7\xf9\xbb\xb7zL\xf5\x7f\x9a\xb1[\xbf\'\xd2\xc5\xb2\x8c[rE\x15\xb02\xc7:\x91S\x1c\xed[\xbe\xcb-\xf5om^\xd7\xfb\xdb_\xe7\xfa^\xb2\xa2\xeap-\xbb\x1f\x17\x1b\x06\xcc^\xa2K\x05\x96:\xcd\x9bN\xb6\xbe\xdf\xb1\xb9\x8e\xdb[k\xff\x00\x0f]\xb5\xd1\xfc\xe7\xe8\xff\x00H\xad\xdd\xd0\xed\xc8\x9c\x96^\xda\x9a\xc6\x8b\x9c\xd7\xb4\x92\xe6\x08\xfd;}-\xde\xeb\x9e[\xb2\xad\x9fN\xdf\xe7?F\x91\xad\x8a\x1a\xf8}=\x96\x10\xfb+\xf7Z\xc2Y\x8fYp\x0ck\x86\xd6\x8b\x9e\xd1g\xa7c\xeb\xfc\xcbn\xab\xfe1Z\xce\xcf\xc2\xae\xe3\x89\xd1\xb1\x18\xfa\xe8n\xdb,\xa8~\x91\xcew\xb2\xc6\xd7m{\xb2^\xcf\xf0vX\xcb=\'\xfb\xff\x00\xc1}2;\xa6\xe2\xddak/\xae\xd7W\xb4\xde\xdfPos\xe3VW[\xbd\x0f\xa7\xfa_}6\xef\xf5?\x9e\xae\xcf\xd1*t\xd3\xd2\xac\xc8\xb2\xa7\xde\xc62\xb7=\xd5\xdfU\x8e\x82w{>\xcd],\xf4\xb1\xdd\xb3\xe8?.\xcf\xa1W\xa6\x95\xde\xf7\xe4\xba\xff\x00\x16\xbe5n\xb5\xff\x00\xa6\xcbn k\\\xf6\x171\xf6\x00\xc7\t\xf5\x8d\xae\xdf\xecw\xf3_N\x97\xff\x00\xa3Wl\xc2\x7f\xa3^E\xad\xa8\x1c\xba\xcb\xcdx\xcem\x8e\xb1\xac\x0e\xf52*\xa5\xaes[\xea9\xae\x7f\xfc\x05\xfe\xb5\x9fe\xff\x00\x08\x87\x8d\x9a1sm\xbf*\xf6\x00\xcd\x19eB\xb7\xd7i\x1e\xea\xeb\xd9M\x9b\xbf5\xbf\xa4\xab\xd7\xf4\xef\xfeF\xfbP\xdf\x92\xfb\xb2M\xd6\xd7Uvd\xb0\xef\xbb\x1d\x90\xe7\x02\xd8\x1e\xca\xf7\xb1\xf7\xe4\xbb\xdc\xff\x00N\xdf\xd2\xfe}U\xa7#\xa2\x0b\xf1\xa8\xc9sf\xcfDm\xdf\xb6\xc0\\\xe1\xd9\xf6\\^[\xe9n\xdb\xfa?zj\xe9\xb0\\\xda\xdf\x1e\xf8{\x98\xd7\x00v\x0f\xf8B\xdb\x19\xff\x00\x81\xfaV\xfb\x13\xb2\xdd\x96V,/\x7f\xa6\x08-k\x85o\x89\x9fM\xf6<\xbbo\xd2W11*\xcau\xb9\x16V0\xb1\x1b\xb4\xe58\x81k\x0bG\xf3u\xd3m\xa6\xcd\xb7:\xcd\x9fA\xcc\xf4\xb1\xd9\xbf\xf4\x7f\xe1\x16\xc3\xc9Z2\xba\xbb\xd8\xc6\xbb\x1a\x9b\x05\x14n\x00V\xc0\xe6{N\xe7Z\xeb\xbds[7\xbd\xce{\x9d\xe9\xd3\xe8\xff\x00\xc5\xa02\xdc\xdc\x99\xc9\xab\xd1\x15>C\x9c\xda\xe08\x1f\xe7Z\xd6\xdd\xb5\xcew\xbfc\xb6~\x8b\xfe.\xd5\xa7\xd5:\xad.}u\xb2\xa7\xd4\xcb\x0c\xbb.\xab\xc3Zk\xe1\xbe\xb0\xaa\xcbY]v\x7f\xa3\xfd_\'\xd3\xfd\x17\xabZ\xa7\x87\x89fNA\xa7\x12\xdb\x05\x1a\x079\xd688{\x9d\xfa0\xcd\xdb\xf1\xff\x00\xb7\xef\xff\x00\xae\xa5\x1dE\xd2H\xfa\xbf\xff\xd3\xe70r.f\x1d\xa3\x1e\xc6z\xcf\xb7\xddu\xaf%\xad%\x9e\xc6G\xa3n\xf7\xbbo\xb2\xcf\xf4\x9e\x9f\xf8%,\xbe\x8dx\xb2\xd7\xdb\x95\x8d\x93\x95\x91\x002\x93k\xfe\x81\xda\xf67\xd4hw\xade\x9e\xa3=K?\xe8&\xdb\xf6lsM\xcf\xc6kli}\xf6\xd9.qp\xf6le\x8d~\xdd\xd4\xfbi\xfeo\xfe\xddQ\xa3=\x96\xd1C\x7fH\xf6V\xe07\x168V\xd6\xb1\xde\xab\x19M\xb6}?\x7f\xd3\xfd\x1f\xfd\xb4\xa2\xb3\xb8Z\x1a6\xe2\nl\xfb6_\xa8\xdb\x9av\xba\xb9$\x13>\xe6l\xa3\xf4\xfbuW\xce/Ks\x9e\xc6\xd5\x9bX\xa0\x87R\x1d\x8fk\xe9\x81\xcb==\xec\xd9\xfa]\xfe\x85\x9e\x8f\xfcw\xe9}\xea>\xbd\x96\xb2\xf7X\xd6\xd8\xfb \xb7\xd4\x13\x0es\x9e\xeb6\x1f\xcd\xfes\x7f\xfdiM\x94\xe5W{\xfe\xc7\x95~\xd3\xa1\xae\xc7\xba\t\xf6\xe9\xea8\xff\x00\xd2\xfe\xa7\xf3i\xa6W\xb9#\xf2V\x80.\x1f\xd3Kl&\xfe\xc6l\xf4\xdf\xa0\x8f\xf0\x8c\xba\xaf\xcf\xdd\xb1\x9b\xee\xfes\xfd"\x1b[\x8b\x95Y\xab\r\xacf\x1dr\xec\x9b\xac\x86\x90v\xfb\xacu\x07c\xdc\xcd\xad\xd9_\xfaO\xd2\xff\x003Z|\xc6Y[\x9b[\xaa\xaf\xd6~\xaf\xdc\xe7\xb5\xa6>\x91\xba\xb6\xfd\'~w\xd1\xdf_\xfaE\x0b\xb1\xb0\xaecO\xa1N.U-\xdd\xf6r\x1c\xdd\xe0\x7f\xa3\xb7\x

In [1]:
import os
from pathlib import Path
import pandas as pd


def save_images_by_label(df, output_dir="output_images"):
    output_base = Path(output_dir)

    for idx, row in df.iterrows():
        img_dict = row["image"]

        # Ensure we have valid data
        if not isinstance(img_dict, dict) or "bytes" not in img_dict:
            continue

        byte_data = img_dict["bytes"]
        path_str = img_dict.get("path", f"image_{idx}.jpg")

        # Get filename (e.g., "Mountain_33.jpg")
        filename = Path(path_str).name

        # Extract label before the last underscore (e.g., "Mountain_33.jpg" -> "Mountain")
        # If no underscore exists, default to the filename stem
        if "_" in filename:
            label = filename.rsplit("_", -1)[0]
        elif "-" in filename:
            label = filename.rsplit("-", -1)[0]
        else:
            label = Path(filename).stem

        # Create target subfolder directory (e.g., "output_images/Mountain")
        label_folder = output_base / label
        label_folder.mkdir(parents=True, exist_ok=True)

        # Write binary bytes to disk
        file_path = label_folder / filename
        with open(file_path, "wb") as f:
            f.write(byte_data)


df = pd.read_parquet(rf"C:\Users\sus14836\Downloads\train-00005-of-00006-1e9efe76b85e7e61.parquet")
save_images_by_label(df, output_dir=rf"E:\Data\vlm\eval\CLRS")

In [15]:
df['image'].iloc[1852]

{'bytes': b'II*\x00\x08\x00\x00\x00\n\x00\x00\x01\x04\x00\x01\x00\x00\x00\x00\x01\x00\x00\x01\x01\x04\x00\x01\x00\x00\x00\x00\x01\x00\x00\x02\x01\x03\x00\x03\x00\x00\x00\x86\x00\x00\x00\x03\x01\x03\x00\x01\x00\x00\x00\x01\x00\x00\x00\x06\x01\x03\x00\x01\x00\x00\x00\x02\x00\x00\x00\x11\x01\x04\x00\x01\x00\x00\x00\x8c\x00\x00\x00\x15\x01\x03\x00\x01\x00\x00\x00\x03\x00\x00\x00\x16\x01\x04\x00\x01\x00\x00\x00\x00\x01\x00\x00\x17\x01\x04\x00\x01\x00\x00\x00\x00\x00\x03\x00\x1c\x01\x03\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x08\x00\x08\x00\x08\x00JTUNXYHXVBVRATP@SO@SOATPCVRFXTIYVN_\\?OL:JG@OL;JG-<9.=:>MJVb^^gd`geafd`cbbcbkjizxv\x93\x8e\x8d\xb0\xa9\xa9\xbc\xb4\xb2\xc4\xbc\xba\xc6\xbf\xbd\xc3\xbe\xbb\xb5\xb0\xac\x93\x8e\x8apkg[WT\\WTXWTUTRWWU^`]adb^ba_cb_cb[]^Z[]^_aeeglimokqmgm_T\\VIRSFMaRWYJOtdg\x98\x88\x89vhh`RRcVVeZ[`XZd_`ljlnmqjjohhligjgehdce``b\\]_]_`^bc`ff_hgZdcT^]Q][P^[O^[N]ZK[XK^YLaZLaZLaZLaZLaZLaZKbZKbZI`XGaXF`WE_VE_VD^UB]TB]T@_V@_W?^V>]U>]U=\\T<[S<[S;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;[R;\\S;\\S;\\S:[R:[R9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YQ8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WO5VM5VM5VM5VM5VM5VM5VM5VM4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UN4UNJUWITVGXVEZUCXSBVRBUQBUQCVRDWSFYUFYU@SO>NK8HE1A>+<9/@<8IES`\\\\gc]gd^fc^ca^a`egerrp\x84\x82\x80\x9d\x98\x97\xb5\xaf\xad\xc3\xbb\xb9\xc3\xbb\xb9\xc4\xbc\xba\xc3\xbb\xb8\xac\xa4\xa1\x8b\x83\x80idaZURRNLWUS]][]^\\\\_^_cbaed_cb[__Z\\^\\\\^``bccffdieag[QYUJQ8+2WKOgX]\x92\x82\x85\x87vxwghn]^eVWbWWg^`icefceecghgljjnjiljjliikefhabd]ab\\`a\\bbaji^gf[edWcaVb`Sa^Q`]P_\\N_ZM`ZM`ZM`ZLaZLaZLaZLaZKaZI`XI`XF`WF`WE_VD^UC]TC]TA_V@_W?^V>]U>]U=\\T<[S<[S;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;[R;\\S;\\S;\\S:[R:[R9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YQ8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WO5VM5VM5VM5VM5VM5VM5VM5VM4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UN4UNKWXKVXGXVDYTBWRAVQ?TO?TO?TO@TPAUPBUQFZVDWS9LH2EA4GC;NJATPTc_[gc\\gc\\fc\\da[a__caijhtsq\x87\x83\x81\xa8\xa3\xa0\xbb\xb5\xb2\xbc\xb4\xb2\xc3\xb9\xb7\xcc\xc2\xc0\xc0\xb6\xb4\xa6\x9b\x99\x80zwa\\YPKJVTS^^\\Z[YY[Zbedcgf`dc_cc]`a[\\^YZ\\ZZ]][`^[`_X_wnuWNSmaeeW[\x8az}fTV\x81np\x87vwhYYYLMeZ]kcfeaccbfgfkgfjhhjjjlkkmijlfhjaef`de^dd_hg`ih_ih\\gfXdbUa_R`]Q`]O`[M`ZM`ZM`ZM`ZM`ZLaZLaZKaZI`XI`XI`XF`WE_VD^UD^UC]TA_V@_W?^V>]U>]U=\\T<[S<[S;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;[R;\\S;\\S;\\S:[R:[R9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YQ8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WO5VM5VM5VM5VM5VM5VM5VM5VM4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UN4UNJXYN\\]FXV=RM<QL;PK;PK;PK;PK;PK<QL?TOCXSDYT@UP;QL>SNF[VPfaYje[hd[gc\\gc\\fb[b`\\b_bebiigvtr\x93\x8f\x8c\xaa\xa4\xa2\xb7\xae\xad\xc3\xb8\xb7\xcc\xc1\xbf\xc6\xba\xb8\xb8\xaa\xa9\x9b\x93\x91ysp\\VVUPPVTSWVTZ\\Zcfedhgcgfeiibfg]`aXY[VVYXW\\ZY^a_d\x8a\x85\x8b\x85\x80\x84\x80x{_SW|mpdTV\x8f|~\x9e\x8b\x8dsbdYIL_SWe\\_e_bjfkiglcbfddffgihikhikfhjdhieijdjj[cc]fe_hg]gfXcaR^\\P\\ZQ][O_ZM`ZM`ZM`ZM`ZM`ZLaZLaZLaZK`YJaYI`XH_WG^VE_VD^UD^UA_W@_W?^V>]U>]U=\\T<[S<[S<[S;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;[R;\\S;\\S;\\S:[R:[R9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YQ8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WO5VM5VM5VM5VM5VM5VM5VM5VM4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UN4UNGWXJ[[BUR9NI8MH9NI9NI:OJ;PK;PK<QL>SN;PK=TND[UBYS>UOE\\VSjd[mg[jeZhc[gc\\gc[eb[c__c`dfclkh{wt\x94\x8d\x8b\xaf\xa5\xa4\xc2\xb5\xb5\xc9\xbb\xba\xc8\xb9\xb8\xc6\xb6\xb6\xb0\xa7\xa5\x97\x8f\x8dsllUQPKIGQPN[\\[_cbbfeeihhllgklbef[\\^WXZXW\\ZZ_^`dttx\x88\x86\x89wrsaVZ{mp~no\x90}\x7f\x9e\x8b\x8d\x83rso_aj\\``VZ]VZfbghfkccfdegdegcdface_cd`debhhdkkW`_[dc]fe\\feXbaS^]P\\ZP\\ZP_ZN`ZM`ZM`ZM`ZM`ZM`ZLaZLaZK`YK`YI`XI`XH_WG^VE^UE^UA_W@_W?^V>]U>]U=\\T<[S<[S<[S;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;[R;\\S;\\S;\\S:[R:[R9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YQ8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WO5VM5VM5VM5VM5VM5VM5VM5VM4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UN4UNASUASU=QO:OJ:OJ;PK<QL<QL=RM=RM<SM>UO:QK=TNG^XH`ZE\\VH_YQjdZmgZjdWfaYfb[gc\\gc\\da^d_adaeebjhd\x7fyv\x9f\x95\x94\xb7\xab\xaa\xc3\xb5\xb4\xca\xba\xba\xd1\xc0\xc0\xbc\xb3\xb2\xaf\xa7\xa5\x8e\x87\x87d_^MKIQPN[\\[[^]]a`chfgkkhlmdgh_ab[\\_ZZ_\\]a`fhgjm\x80\x80\x82ropc[]f[]|mm}lm\x8f|~\x8e{}\x8c{}\x80svi^bYRU\\X]cafedhdegbce^`bY]^W[\\X]][aa_eeXa`Yba[dcZdcYcbWa`T_]S^\\P_[O`ZO`ZN`ZM`ZM`ZM`ZM`ZLaZLaZK`YJaYI`XH_WG^VG^VG^VA_W@_W?^V>]U>]U=\\T<[S<[S<[S<[S<[S<[S<[S<[S<[S<[S<[S;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;[R;\\S;\\S;\\S:[R:[R9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YQ8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WO5VM5VM5VM5VM5VM5VM5VM5VM4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UN4UN<OQ=OQ=QO=RM=RM>SN>SN>SN=SM;RL;RL:QK=TNBYSD]WJc]OhbQjdPicYlfWhbTc^Ud_Ygb\\gc\\fa]d`_c`ab^db_qki\x88~}\xa1\x95\x95\xba\xaa\xaa\xc9\xb9\xb9\xd3\xc1\xc1\xc5\xbb\xba\xc0\xb8\xb6\xa8\x9f\xa0~yy`^\\YYW\\]\\Z^][_^]caaffdhicgh`cd]^a[\\`\\^baikekmptuxxxqlm[RSqcdyjk\x83pr\x8dz|\x94\x83\x85\x8f\x82\x85~swh_c[V[]Y_`_c_`b]_`X\\]UYZSWXTXYV\\\\Y``YbaXa`W`_Wa`XbaYcbWa`U_^Q_[O`ZO`ZO`ZN`ZM`ZM`ZM`ZLaZLaZLaZK`YI`XH_WH_WG^VG^VA_W@_W?^V>]U>]U=\\T<[S<[S<[S<[S<[S<[S<[S<[S<[S<[S<[S;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;[R;\\S;\\S;\\S:[R:[R9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YQ8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR8YR7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WO5VM5VM5VM5VM5VM5VM5VM5VM4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UL4UN4UN9OO<RR>SQ?TP?SO>SO>SO=SN<QM9PK6NH2ID:RL>WQ?YSGa[SlgVpjQkeVkeUhbRc_Sc_WfbZgc[fc]fb^ca_a_dc`iectll\x8b\x81\x81\xab\x9e\x9e\xc3\xb4\xb4\xcc\xbd\xbd\xc8\xbf\xbc\xc7\xc0\xbc\xba\xb2\xb0\x9a\x93\x92xtrfc`a_]``_]]\\\\^]acbcefbee`cd^`aZ\\_Y\\^`eh_cf_`bzyy\x86\x81\x83sjkzon\x82uu\x7fop\x80pq\x88y{\x93\x87\x8a\x91\x86\x8a\x7fvzibh\\V\\XVZWZ[X[\\W]]U[[SXXSYXX^\\Y_^V_]W_]V^[U^[W`^Yb`Xa^U^[R_ZP`ZP`ZO`ZO`ZN`ZM`ZM`ZLaZLaZLaZKaYI`XH`XH`WG_VF^VA_W@`W?_W>^V>^U=]U=\\T<[S<[S<[S<[S<[S<[S<[S<ZR<ZR<ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;[R;[R;[R:ZR:ZR9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9ZQ9YQ8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YP8YQ8YR8YR8YR8YR8YR8YR8YR8YR8XR8XR8XR8XR8XR8XR8XR8XR8XR8XR8XR8XR8XR8XR8XR8XR8XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ7XQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WO5VM5VM5VM5VM5VM5VM5VM5VM4UL4UL4UL4UL4UL4UL4UL4UL4UL4UK4UK4UK4UK4UK4UL4UL4UL4UL4UM4UM4UM4UM4UM4UM4UM4UN4UN;TQ=VS@WTBVT@TR?SQ?TR?UR=SP8NK3LH0IE4MI:SO>YTB]XHc^MhcRmhPidOfbOebOdbQdbTecXfd\\gf]fe]cb`cbaaaecdwsr\x94\x8f\x8e\xb0\xaa\xaa\xbe\xb8\xb8\xc3\xbf\xb6\xc6\xc2\xb9\xc4\xc0\xb7\xb5\xaf\xa8\x96\x8f\x89xpkka^ka_d[Y`YXe`_ebaa`__``^`_X\\[VYYd_eb]cfadsmo\x82|~\x88\x82\x82\x83~|}uswomphfyoo\x8f\x85\x87\x9b\x90\x94\x92\x87\x8c}ryeZbVSWT\\ZX`]_gd^fdW`]Ya\\_ea[a]SYUX^ZZ_YW\\VW\\VZ_Y[`ZY^XU^YS_[R`[Q`[P_ZP_ZN`ZM_YL`ZMb[Mb[KbZJaYGaXGaXE`WD_VAaX@aX?`W?`W>_V=^U=]T=\\T=\\T<[S<[S<[S<ZR<ZR;YQ;YQ;YQ;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XQ9XR9XR9XR9XR9XR9XR9XR9XR8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM5TL5TL5TL5TL5TL5TL5TL5TL5UK5UJ5UJ5UJ5UJ5UJ5UK5TL5TL5TL5TN5TN5TN5TN5TO5TO5TO5TN5TNB[XB[XBXVAUS?SQ>RP=RO=SP<RO9OL6NJ8QM;TP>WS>YT?ZU@[VC^YE`[F]ZF\\YG]ZH][K_]Pa_UcaZec\\ed]cc_cb_`__^^khh\x84\x80\x7f\xa0\x9a\x9a\xaf\xa9\xa9\xbf\xbb\xb2\xc2\xbe\xb5\xc6\xc2\xba\xc4\xbd\xb7\xaf\xa8\xa2\x8e\x85\x82ukij`^`WV[TR\\WV^\\Z^^\\\\]\\Z]\\Z^]\\__^Y_^Y_`[_hbdrln{uv\x82}{\x87\x7f}womxpn{rr\x7ftw\x92\x87\x8b\x8f\x84\x89ujqh]eb^bX\\[X][_cbafd^c``fbchd\\b^W\\XZ_[Z_YV[UV[UY^XZ_YY^XV_[Ua]Ta\\Sa\\Ra\\Qa[Pa[Oa[Na[Mb[Mb[KbZKbZHbYGaXF`WF`WAaX@aX@aX?`W?_V>^U=]U=\\T=\\T<[S<[S<[S<ZR<ZR<ZR;YQ;YQ;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XQ9XR9XR9XR9XR9XR9XR9XR9XR8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM5TL5TL5TL5TL5TL5TL5TL5TL5UK5UJ5UJ5UJ5UJ5UJ5UK5TL5TL5TL5TN5TN5TN5TN5TO5TO5TO5TN5TNAYW?WU@VS@TR>RP<PN<PN<QO<RO;QN;QN<TP=VR?XT>XT<WR<WR=XS?ZU?WT@VTBWTDYVH\\ZN_^TbaYdc[ed]dc`dc_a`\\[\\a_`soo\x8a\x85\x85\x9a\x95\x95\xb4\xb0\xa8\xbc\xb8\xb0\xc6\xc1\xbb\xcb\xc5\xbf\xc2\xbb\xb5\xa8\xa0\x9c\x87}{mca`WV\\US[WU\\YX[[YYYYWZYZ^]_aa`[aa\\ba\\`a]^fabpjj}wu\x87\x80~\x81zx}usqhhzps\x84y}\x86{\x80zovlaic]aUVUPQORSRWWVXYV]`]ada\\`\\[_\\[_\\Y]XUZUTYSV[UX^WY^XWa\\Vb^Ua]Ta]Sb]Ra\\Qb\\Pb\\Nb[Mb[Mb[KbZKbZHbYGaXGaXGaXBaXAaX@aX@`W?_V?^V>]U>]U=\\T<[S<[S=[S=[S<ZR<ZR<ZR;YQ;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XQ9XR9XR9XR9XR9XR9XR9XR9XR8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM5TL5TL5TL5TL5TL5TL5TL5TL5UK5UJ5UJ5UJ5UJ5UJ5UK5TL5TL5TL5TN5TN5TN5TN5TO5TO5TO5TN5TN<RP:PN<QO>RP=QO;OM:NL;OM;PN<RO<RO<RO<UQ>WS>WS=WR=XS>YT@[V@WT@VTBVUDXVG[YL^\\R`_WbaZcb\\dcaeebdd___^]^hdextu\x86\x82\x82\xa4\xa1\x9a\xb7\xb3\xad\xc5\xc0\xba\xc7\xc2\xbc\xc7\xc1\xbb\xbe\xb6\xb3\xa2\x98\x96|sqg^\\b[Yb\\[^ZYXWUWWUXZYY][\\^^hcigbhfaed`aeabkeermjxsp\x89\x83\x80vnlsjjxoq{quzot{pwpemaY]]YXPLKKHGMJIOLKWUT`^]__]^`]\\]ZW[WSXTRWRSXSU[UW]XV`\\Ua]Ua]Ta]Sa\\Qa\\Qa\\Pa[Na[Na[Mb[Lc[KbZJcZHbYHbYHbYCaYBaYA`XA`X@_W?^V>]U>]U>]U=\\T=\\T=[S=[S=[S<ZR<ZR<ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XQ9XR9XR9XR9XR9XR9XR9XR9XR8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM5TL5TL5TL5TL5TL5TL5TL5TL5UK5UJ5UJ5UJ5UJ5UJ5UK5TL5TL5TL5TN5TN5TN5TN5TO5TO5TO5TN5TN:PN:PN9NL:MK:MK9MK9MK9MK:NL;QN<RO=SP=UQ?XT?XT>WS>XT@ZUB\\WBYVAWUBWUCWVEXWIZYM\\\\R^^V__Zba_eecggdedaaabaalijwtu\x92\x90\x89\xae\xab\xa5\xc0\xbc\xb6\xbf\xba\xb5\xc4\xbe\xba\xcc\xc4\xc1\xbb\xb3\xb0\x97\x8e\x8cvnljb`g`^^YXVTRVVTZ[XY[XXZXhdjfchgbfgcdhdeiddhc`fa^ytq\x7fxv\x7fwv\x82y{}twvlqqgmlaii^c_TVRGHODFOGHPHHWQQc_^gec__]ZZXVWUSVSRVRQWSSYUV\\XV_[T`\\T`\\T`\\S`\\Q`[Q`[O`ZN`ZNa[Mb[Mb[KbZKbZJcZIcZIcZDbYCaYBaYB`XA_W@^V?^V?]U?]U>\\T>\\T>\\T=[S=[S<[S<ZR<ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XQ9XR9XR9XR9XR9XR9XR9XR9XR8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM5TL5TL5TL5TL5TL5TL5TL5TL5UK5UJ5UJ5UJ5UJ5UJ5UK5TL5TL5TL5TN5TN5TN5TN5TO5TO5TO5TN5TN:PN;QO9NL8KI:MK;NL;NL:NL;OM=QO?TQ@VSAWTAYU@YU?XT=VR>WS@YUBXVBWVBVUBVUDVVFWWIYXMZZQ\\\\V^^Zaa`dedffbcc```edemlm}}v\x9b\x99\x94\xb2\xaf\xaa\xb8\xb4\xb0\xc1\xbc\xb8\xce\xc7\xc4\xc9\xc1\xbe\xb1\xa9\xa7\x90\x88\x86womhb_]YVZWTXXUWXUXYVZ\\Zb`eb`edadgdeieffbbb][]YVgb_\x82}z\x8d\x86\x85\x8b\x82\x84\x86}\x80zquh^dg\\dfY_TCERAD[KNbUV_ST`VWiaamgg`^\\YYWUVTUWTTXTRXTTZVW^[W`]Va]Ua]T`\\T`\\R`[Q`[Pa[Oa[Na[Mb[Mb[Lc[Lc[KbZJcZJcZFbZDaZDaYC`XB_WA^W@^V@^V@^V?]U>\\T>\\T>\\T=[S<[S<[S<[S;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XQ9XR9XR9XR9XR9XR9XR9XR9XR8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM5TL5TL5TL5TL5TL5TL5TL5TL5UK5UJ5UJ5UJ5UJ5UJ5UK5TL5TL5TL5TN5TN5TN5TN5TO5TO5TO5TN5TN8ML9NL9MK;NL?RPATRBUSATR@TRBVTDXVBWTCYVBYVAXU>WS<UQ<UQ>WSBXVCXWCWVCVUDVVFWWIXYLZZO[[Q[\\S[\\Z___cd`bd__`bcdiijkkf\x84\x83~\xa0\x9e\x9a\xb3\xb0\xac\xc0\xbb\xb8\xca\xc3\xc0\xc9\xc1\xbf\xc1\xb9\xb7\xac\xa4\xa2\x8b\x83\x81lec`\\Yb_\\][WRRNVWSab`a_db`edbeecdebcb^^_[X]XU`\\Ynif\x83~}\x8a\x83\x84\x86~\x81wnrf]c]S[YJO\\FIgRU}ik\x87uw{klm_ak``kbbb]\\ZXVWWUXZXW[XUZXU[YYa^Xc_Wb^Wb^Vb^Ua]Ta]Ra\\Rb\\Qb\\Oa[Na[Mb[Mb[Lc[Lc[Lc[Kc[GaZFaZF`YD_XD_XC_WA^V@^V@^V?]U?]U>\\T>\\T=\\T<[S<[S<[S;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XQ9XR9XR9XR9XR9XR9XR9XR9XR8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM5TL5TL5TL5TL5TL5TL5TL5TL5UK5UJ5UJ5UJ5UJ5UJ5UK5TL5TL5TL5TN5TN5TN5TN5TO5TO5TO5TN5TN9ML7KJ:ML?POBTREXVH[YH[YG[YEYWCWU@TR@UR@VS?UR>UR>UR>UR=VR@VUBVWBVWCVWEWWGXXJYYLYZOZ[PYZMTVPWXSXYZ^_`cd`aceegggbqql\x88\x87\x83\xa6\xa3\xa0\xbb\xb6\xb3\xc2\xbd\xba\xc5\xbd\xbb\xc8\xc0\xbe\xc1\xb9\xb7\xa6\x9e\x9c\x7fxvhb`c^[_\\YXXSXXS\\\\Y\\Z_b`dgehgefb`a^[Z]YV^ZW_ZW`\\Yoih\x84~\x80\x84}\x7frko`W]OEM[KQ}dg\x8ctw\xa0\x8a\x8c\xa5\x90\x92\x90}~vegj]]i_`h`ab]\\][[[\\[X\\[W\\[X^][caYd`Xc_Xc_Wb^Ua]S`\\R`\\Sb]Rc]Pb\\Nb\\Nb[Mb[Mb[Lb[KbZKbZI`ZG`ZG`ZF_YE_YD^XC^WC^WA^V?]U?]U>\\T=\\T=\\T<[S<[S<[S=\\T<[S<[S;ZR;ZR;ZR;ZR;ZR;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UK6VK6VK6VK6VK6VK6UK6UM6UM6UM6UO6UO6UO6UO6UO6UP6UP6UO6UO>RQ<PO>POBRQCSRFWVJ\\ZK^\\I\\ZBVT=QO?SQ?SQ?SQ>TQ>TQ?UR?UR>URBWWBVW?ST>QR?QRCTTHXXNZ\\OZ\\JTUEMOFNPFLMRWXbfg^`b`cdegcfgcuup\x91\x8f\x8c\xad\xa9\xa6\xbd\xb8\xb5\xc5\xbe\xbc\xc9\xc1\xbf\xca\xc2\xc0\xbb\xb3\xb1\x9b\x93\x91wpm`\\X\\YU^]XZZTTTPWUZ^\\adceecd_]^ZYWZXT\\YV^ZW]XUf`_xrt\x7fy{pjm^W\\ZQYrch\x97}\x80\xa3\x89\x8c\xac\x94\x97\xa8\x92\x94\x94\x80\x82}jlm``i^`nefgbc`^_\\]\\[]][_`\\bb]ccZcaYc`Yd`Wb^T`\\S^ZR_[Sa\\Sb]Qb\\Pb\\Ob\\Na[Mb[LaZLaZKbZI`ZH`ZH`ZG_YF_YF_YE^XD_XB^W@]U?]U>\\T=\\T=\\T=\\T<[S<[S>]U=\\T<[S;ZR;ZR;ZR;ZR<[S;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6VL6VK6VK6VK6VK6VK6VL6UM6UM6UM6UO6UO6UO6UO6UP6UP6UP7VP7VP@SS?RR@RQBRQDTSGWVIZYI[YCVT;NL6JH?SQ?SQ?SQ?SQ>TQ>TQ>TQ>TQBVW@SV=PR<NP>PRCTVHWXKYZKWYGRTDNODMN@HJMTUbgi^cd^cc^`^ac`jkh}|y\x99\x96\x94\xb4\xb0\xad\xc4\xbd\xbb\xc7\xbf\xbd\xc9\xc1\xbf\xc6\xbe\xbc\xb2\xaa\xa7\x8e\x88\x84lgc\\YT\\YT\\ZUXXSWV[ZY^]]^\\\\\\YXYXWUXWSZXU^ZW[WT_ZYjdfoikkehkdjxqx\x8f\x81\x86\xa4\x8b\x8c\xa8\x90\x91\xa4\x8d\x8e\x99\x83\x85\x8f{|\x87uwxjjh\\^ofghac_]^]\\^_`bade`ef^ce\\cb[da[daYc_Va]T_[S_[Ta\\Sb]Qb\\Qb\\Ob\\Na[Mb[LaZLaZLaZJ`ZJ_ZJ_ZI`ZH_YG_YF_YE_XC^WA]U?]U?]U=\\T=\\T=\\T<[S<\\S>]U=\\T<[S;ZR;ZR;ZR;ZR<[S;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6VL6VK6VK6VK6VK6VK6VL6UM6UM6UM6UO6UO6UO6UO6UP6UP6UP7VP7VP>PP=OO?POAQPBRQEUTHXWGWV?QP5HF1DB?RP>RP>RP>RP=RP=SP<RO<RO<PR;NR<OR@RUEWYHY[IWZFTVHUVNY[JUVGQR=FGIPR`fi\\cdY`a]a^_a^cdannl\x86\x83\x82\xa3\x9e\x9d\xb9\xb1\xb0\xc1\xb9\xb7\xc8\xc0\xbe\xcc\xc4\xc1\xc4\xbb\xb9\xaa\xa3\xa0\x87\x81}kga`\\V^\\U^\\WYX]ZY]ZZ\\ZZZYYYZYWZYV[ZV^\\X\\XU\\XWa\\]c^`e`brlq\x8a\x83\x8a\xa0\x92\x96\xab\x92\x92\xa6\x8f\x8f\x95\x7f\x7f\x85pq\x89vv\x93\x82\x83\x87yymbdofgibdb_``_abcebfhaeh^cf]dc\\eb\\eb[daXb^U`\\T_[Ta\\Sb]Ra\\Qb\\Pb\\Na[Na[LaZLaZLaZK_ZK_[J_ZJ_ZI_ZH_YG_YF_YD^XB]V@]V?]U>]U=\\T=\\T;\\S;\\S>]U=\\T<[S;ZR;ZR;ZR;ZR<[S;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6VL6VK6VK6VK6VK6VK6VL6UM6UM6UM6UO6UO6UO6UO6UP6UP6UP7VP7VP=OO<NN>ONAPPCRRFVUIYXHXWBRQ7HG1DB=PN=PN<PN<PN<PN;PN;PM;OM@SU?RV>PT>PTASVFVYHWZHVYIWYKWXEPR@KL5?@@IKXabV^`T\\^_db\\`^_`_jjhzxw\x8d\x89\x88\xa5\x9f\x9d\xba\xb3\xb1\xc8\xbf\xbd\xcb\xc2\xc0\xc9\xc0\xbe\xbf\xb8\xb4\xa7\xa1\x9b\x85\x80zid^]YR\\ZUXX]ZY^[[]\\\\\\\\\\\\]\\Z]\\X]\\X]\\X\\[W^ZX_[[]YZ^Y\\jdj\x80y\x80\x96\x89\x8c\xa5\x8f\x8d\xa1\x8c\x8a\x90|z\x82po\x8c||\x9c\x8e\x8d\x90\x83\x84qghlcdidegegedfbcf`be^be^ae]cc\\eb]fc\\ebYc_Va]T`\\T`\\Ta]Ra\\Qb\\Qb\\Na[Na[M`ZLaZLaZL_[L_[K_[K_ZJ_ZI_ZH_YG_YE_XC^WB^W@^V>]U=]T<]T;\\S;\\S>]U=\\T<[S;ZR;ZR;ZR;ZR<[S;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6VL6VK6VK6VK6VK6VK6VL6UM6UM6UM6UO6UO6UO6UO6UP6UP6UP7VP7VP=OO<NN@PPDRRFTTJXXM\\\\L\\[GWV>NM7JH;NL;NL:NL:NL:NL;OM;OM;OMASVBTXASW@RVASWDTWFUXGVYFTW@MO8CE3>@,78:DEQ[\\S]^Xab_cbY]\\]_^iihrqp|yx\x92\x8e\x8b\xb1\xaa\xa8\xc3\xba\xb9\xc6\xbc\xbb\xc7\xbd\xbb\xc9\xc0\xbd\xbf\xb8\xb2\xa0\x9a\x94ytm_[SWTOUVZXY]Z[]]]]]]]\\\\Z\\]X]]Y\\[W\\[W^[Y^ZZZVWXSV\\W\\f`g{ps\x95\x83\x7f\x9b\x88\x84\x97\x85\x82\x92\x82\x80\x98\x8a\x88\x9c\x90\x8f\x89~~lcbd]]gcdigjggibbf]^b\\^b^`d\\aa\\b`\\da[daZc`Wa]U`\\T`\\Ta]Ra\\Ra\\Qb\\Oa[Na[M`ZLaZLaZN_[M^[L_[L_[K_ZJ_ZI`ZH`ZF_YD^XC_W@_W?^V>]U<]T;\\S;\\S>]U=\\T<[S;ZR;ZR;ZR;ZR<[S;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6VO6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6UM6VL6VK6VK6VK6VK6VK6VL6UM6UM6UM6UO6UO6UO6UO6UP6UP6UP7VP7VP>PP>PPBRRFTTGUUJXXM\\\\M]\\IYXAQP;MK:MK:MK;NL;OM;OM<PN=QO=QO;MP>PTDVZHZ^HZ^EVZBQU@ORBPS?LO0=>-8:+688CDLVWPZ[]gh\\`_Y]\\^`_eeeihgqnm\x85\x80\x7f\x9f\x98\x96\xb5\xac\xaa\xc0\xb6\xb5\xc7\xbd\xbb\xcb\xc3\xbf\xc8\xc1\xbb\xb5\xaf\xa9\x95\x91\x88rne[XRUVZXY][\\^[\\\\YYYYYW\\]Xaa\\_^Z^]Y\\ZXZWWXTUWRUWRWWRXe\\]\x80pk\x8c|x\x97\x88\x83\x9a\x8c\x89\x97\x8a\x87\x8b\x80~wmle][^XXc^_fcffeicbf^^c\\]b]^cZ^_Y_]Zb_Zc`Yb_Wa^Va]Ua]Ta]Ra\\Ra\\Qb\\Pa[Na[M`ZM`ZLaZN_\\O_\\N^[L_[L_[K_ZI`ZH`ZF_YE_YD`XA_W?^V>]U<]T;\\S;\\S>]U=\\T<[S;ZR;ZR;ZR;ZR<[S;ZR:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ:YQ9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP9XP8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ8WQ6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6WP6W

In [14]:
df

                                                  image  label
0     {'bytes': b'II*\x00\x06\x06\x03\x00\x7fNH8KE5I...      0
1     {'bytes': b"II*\x00\x08\x00\x00\x00\n\x00\x00\...      0
2     {'bytes': b'II*\x00\xea\xfd\x02\x00\x7fach]`f[...      0
3     {'bytes': b'II*\x00\x08\x06\x03\x00\x7f\x9f\xa...      0
4     {'bytes': b'II*\x00\xc0\xfc\x02\x00\x7f\x81\x7...      0
...                                                 ...    ...
2495  {'bytes': b'II*\x00\x1a\x06\x03\x00~Tbbess[iia...      4
2496  {'bytes': b'II*\x00\x86\x03\x03\x00\x7f*8C,=E)...      4
2497  {'bytes': b'II*\x00\x1e\x06\x03\x00HTVQDF@qrl\...      4
2498  {'bytes': b'II*\x00\n\x06\x03\x00\x7fjyfy\x88u...      4
2499  {'bytes': b'II*\x00\x02\x06\x03\x00\x7fA@P68G6...      4

[2500 rows x 2 columns]